### PR TITLE
Setup frontend

### PR DESCRIPTION
**Pull request by arreche**

### CODE REVIEW

**Comment by CasiOo** [comment]
I'm not sure we can use Webpack for html files?
Our index.html is currently placed in /build/app/index.html when it should be in the root /build.

We could go with an index.html file in our project root

**Comment by arreche** [comment]
It works on OS X and Linux but you are getting this error on Windows 10

```
ERROR in ./styles.sass
Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/css-loader/index.js in C:\Users\Stephan\Desktop\jstogether\Project-3-todo\todo-react/app
 @ ./styles.sass 4:14-117

ERROR in ./styles.sass
Module not found: Error: Cannot resolve 'file' or 'directory' ./../node_modules/style-loader/addStyles.js in C:\Users\Stephan\Desktop\jstogether\Project-3-todo\todo-react/app
 @ ./styles.sass 7:13-68
```

I don't know if it is related to https://github.com/jtangelder/sass-loader/issues/127

**Comment by CasiOo** [comment]
Looks to be related, but it should already be resolved in our version of sass-loader?

**Comment by arreche** [comment]
The problem appears running `npm i node-sass` on a [Windows 10](http://dev.modern.ie/tools/vms/mac/).

**Comment by CasiOo** [comment]
We should probably add the public folder to .gitignore

**Comment by arreche** [comment]
I am not sure yet... Meanwhile the generated `bundle.js` is already being ignored.

```bash
cat .gitignore
node_modules
data/
public/build.js
```

**Comment by CasiOo** [comment]
PR looks good :thumbsup:

**Pull request merged**
